name: CI/CD AKS Microservices

on:
  push:
    branches:
      - master
  pull_request:

env:
  ACR_NAME: demoaksacr9nzhtn
  AKS_RESOURCE_GROUP: demoaks-rg
  AKS_CLUSTER_NAME: demoaks-aks
  K8S_NAMESPACE: demo
  SERVICES: gateway user order

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    outputs:
      image-tags: ${{ steps.set-tags.outputs.image-tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git SHA for image tagging
        id: set-tags
        run: |
          SHA=$(git rev-parse --short HEAD)
          echo "SHA=$SHA" >> $GITHUB_ENV
          TAGS=""
          for svc in ${{ env.SERVICES }}; do
            TAGS="${TAGS}${svc}=${{ env.ACR_NAME }}.azurecr.io/${svc}:${SHA} "
          done
          echo "::set-output name=image-tags::$TAGS"

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push Docker Images
        run: |
          for svc in ${{ env.SERVICES }}; do
            IMAGE=${{ env.ACR_NAME }}.azurecr.io/$svc:$SHA
            echo "Building $IMAGE..."
            docker build -t $IMAGE ./$svc
            docker push $IMAGE
          done

  deploy-to-aks:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} \
                                 --name ${{ env.AKS_CLUSTER_NAME }} \
                                 --overwrite-existing

      - name: Update Kubernetes manifests with versioned images
        run: |
          SHA=$(git rev-parse --short HEAD)
          for svc in ${{ env.SERVICES }}; do
            kubectl set image deployment/$svc $svc=${{ env.ACR_NAME }}.azurecr.io/$svc:$SHA -n ${{ env.K8S_NAMESPACE }}
          done

      - name: Rollout deployment and wait for readiness
        run: |
          for svc in ${{ env.SERVICES }}; do
            kubectl rollout status deployment/$svc -n ${{ env.K8S_NAMESPACE }} --timeout=120s
          done

      - name: Verify all pods are running
        run: |
          kubectl get po -n ${{ env.K8S_NAMESPACE }}
          kubectl get svc -n ${{ env.K8S_NAMESPACE }}

  rollback-on-failure:
    name: Rollback on failed deployment
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} \
                                 --name ${{ env.AKS_CLUSTER_NAME }} \
                                 --overwrite-existing

      - name: Rollback deployments
        run: |
          for svc in ${{ env.SERVICES }}; do
            echo "Rolling back $svc to previous revision..."
            kubectl rollout undo deployment/$svc -n ${{ env.K8S_NAMESPACE }}
          done
